--HSQLDB HQL 任务 org.hibernate.tool.hbm2ddl.SchemaExport Executing import script: /import.sql
--该操作语句解析是按行进行的，所以HQL语句要按行录入。

--清理表hibernate_unique_key
--DROP TABLE IF EXISTS hibernate_unique_key;
--构建表hibernate_unique_key
--CREATE TABLE hibernate_unique_key(next_hi int GENERATED BY DEFAULT AS IDENTITY (start with 1),PRIMARY KEY (next_hi));
--插入默认值
--INSERT INTO hibernate_unique_key(next_hi) VALUES(1);
INSERT INTO t_admin VALUES ('1', '0', 'a', 'a');

INSERT INTO t_user VALUES ('1302597334484', '2009001', '000000', '2', '2009001');
INSERT INTO t_user VALUES ('1302597522890', '001', '000000', '1', '001');
INSERT INTO t_user VALUES ('1302597776312', '2009002', '000000', '2', '2009002');
INSERT INTO t_user VALUES ('1302597814140', '002', '000000', '1', '002');
INSERT INTO t_user VALUES ('1302597962890', '2009003', '000000', '2', '2009003');
INSERT INTO t_user VALUES ('1302597992046', '000000', '000000', '1', '003');
