package com.sky.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.GenericGenerator;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "t_doc")
public class Tdoc {

	// Fields
	@Id
	@GeneratedValue(generator = "generator")    
	@GenericGenerator(name = "generator", strategy = "uuid")  
	private String id;

	private String mingcheng;

	private String fujian;

	private String fujianYuanshiming;

	private String type;

	private String del;

	@OneToMany(targetEntity = Attachment.class, mappedBy = "doc", fetch = FetchType.LAZY)
	@Cascade(value = (org.hibernate.annotations.CascadeType.ALL))
	private Set<Attachment> attachments;

	// Constructors

	/** default constructor */
	public Tdoc() {
	}

	/** full constructor */
	public Tdoc(String mingcheng, String fujian, String fujianYuanshiming,
			String del) {
		this.mingcheng = mingcheng;
		this.fujian = fujian;
		this.fujianYuanshiming = fujianYuanshiming;
		this.del = del;
	}

	public void addAttachment(Attachment attachment) {
		if (this.attachments == null) {
			this.attachments = new HashSet<Attachment>();
		}
		this.attachments.add(attachment);
	}

	// Property accessors

	public String getMingcheng() {
		return this.mingcheng;
	}

	public void setMingcheng(String mingcheng) {
		this.mingcheng = mingcheng;
	}

	public String getFujian() {
		return this.fujian;
	}

	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

	public String getFujianYuanshiming() {
		return this.fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming) {
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getDel() {
		return this.del;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Set<Attachment> getAttachments() {
		return attachments;
	}

	public void setAttachments(Set<Attachment> attachments) {
		this.attachments = attachments;
	}

}