package com.orm;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class Tdoc
{

	// Fields

	private String id;

	private String mingcheng;

	private String fujian;

	private String fujianYuanshiming;
	
	private String type;

	private String del;

	// Constructors

	/** default constructor */
	public Tdoc()
	{
	}

	/** full constructor */
	public Tdoc(String mingcheng, String fujian, String fujianYuanshiming,
			String del)
	{
		this.mingcheng = mingcheng;
		this.fujian = fujian;
		this.fujianYuanshiming = fujianYuanshiming;
		this.del = del;
	}

	// Property accessors

	public String getMingcheng()
	{
		return this.mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getFujianYuanshiming()
	{
		return this.fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getDel()
	{
		return this.del;
	}

	public String getType()
	{
		return type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getId()
	{
		return id;
	}

	public void setId(String id)
	{
		this.id = id;
	}


}